name: Photo Studio-John Ferguson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8785302829928696
title: John Ferguson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#77aee1'
    - '#bbd9e6'
    - '#7c4904'
    - '#f4a52c'
  brandStrength: 0.5
  lightness: 0.15452179545536637
  saturation: 0.7135113619733602
  rhythmicContrast: 0.6493745883926749
purpose: []
